ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product/<int:id>', views.product, name='product'),
    path('cart', views.cart, name='cart'),
    path('catalog/<int:page>/<int:limit>', views.catalog, {'gen': None}, name='catalog'),
    path('catalog/<str:gen>/<int:page>/<int:limit>', views.catalog, name='catalog_gen'),
    path('scout', views.scout, name='scout'),
    path('search', views.search, name='search'),
    path('add-to-cart', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart', views.remove_from_cart, name='remove-from-cart'),
    path('buy-keys', views.buy_keys, name='buy-keys'),
    path('product-add', views.product_add, name='product-add'),
]

gs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ecommerce.urls')),
    path('', include('customer.urls')),
    path('', include('review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import  views

app_name = 'review'

urlpatterns = [
    path('review/<int:prod_id>', views.review, name='review'),
    path('review/remove_review', views.remove_review, name='remove_review')
]

review/models.py
from datetime import datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.contrib.auth.models import User
from ecommerce.models import Transaction, Product

class Review(models.Model):
    title = models.CharField(max_length=64, blank=True, null=True, help_text='Enter a title for the review')
    text = models.TextField(blank=True, null=True, help_text='Enter your review of the product')
    rate = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)],
                                       help_text='Enter your rate for the product (1-10)')
    date = models.DateField(blank=True, default=datetime.now)

    user = models.ForeignKey(User, on_delete=CASCADE)
    trans = models.OneToOneField(Transaction, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('trans', 'product'),)
        ordering = ['product', 'date']
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.trans.__str__()

    def get_absolute_url(self):
        return reverse('review-detail', args=[str(self.id)])

review/forms.py
from django import forms
from review.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'text', 'rate')

review/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render
from django.template.defaulttags import register
from ecommerce.models import Product, Transaction
from .models import Review
from .forms import ReviewForm


@register.filter
def get_review(reviews, index):
    return reviews[index].text


def review(request, prod_id):
    current_product = Product.objects.get(id=prod_id)
    is_bought = Transaction.objects.filter(customer=request.user, key__product__id=prod_id, state=Transaction.success).exists()
    user_review = Review.objects.filter(product_id=prod_id, user=request.user).first()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            new_review = form.save(commit=False) # Don't save it yet
            new_review.product = current_product # Add product
            transaction = Transaction.objects.filter(customer=request.user, key__product__id=prod_id).order_by('-date_time').first()
            new_review.trans = transaction
            new_review.user = request.user
            new_review.save()
            return redirect(f'/review/{prod_id}')
    else:
        try:
            base_query = Review.objects.filter(product_id=prod_id)
            current_reviews = base_query.exclude(title__isnull=True).order_by('-date')
            review_count = current_reviews.count()
            rate_count = base_query.count()
            total_rate = base_query.aggregate(Sum('rate'))["rate__sum"] or 0
            product_rate = (total_rate / rate_count) if rate_count != 0 else 0
            form = ReviewForm()
        except Product.DoesNotExist:
            return HttpResponseNotFound("The the product with the ID:" + prod_id + " does not exist") 

    context = {
        'is_bought': is_bought,
        'user_review': user_review,
        'reviews': current_reviews,
        'number_review': review_count,
        'rate_count': rate_count,
        'product_rate': product_rate,
        'product': current_product,
        'form': form,
    }
    return render(request, 'review/review.html', context)


@login_required
def remove_review(request):
    review_id = request.POST.get("review_id")
    review_to_remove = Review.objects.filter(id=review_id)
    review_to_remove.delete()

    return redirect(f'/review/{request.POST.get("prod_id")}')

review/templates/review/review.html
{% extends "ecommerce/base.html" %}
{% block content %}

<!--Start Container-->

    <div class="container p-3">
        <div class="row">
            <div class="col-sm-6 ">
                <a class="" href="{% url 'ecommerce:product' id=product.id %}">
                    <div class="d-flex justify-content-center">
                        <img class="w-75  border-img" src="{{product.pic.url}}" alt="Image not found" onerror="this.onerror=null;this.src='/media/products/images/img_default.jpg';">
                    </div>
                </a>
            </div>
            <div class="col-sm-6">
                <h2 class="h4 fw-bold title-bar t-shadow text-start text-uppercase pb-3">{{product.name}} reviews page</h2>
                <div class="rounded-2 border-product badge-product">
                    <div class="row">
                    <!--Start Number Review-->
                        <div class="col-4 p-1 t-shadow">
                            <div class="text-light text-center">
                                <h3 class="h6 text-light  text-center pt-3">Ratings</h3>

                                <div class="row">
                                    <div class="col-6 text-end">
                                        <span class="material-icons">
                                          thumbs_up_down
                                        </span>
                                    </div>
                                    <div class="col-6">
                                        <h3 class="h6 t-shadow text-light text-start fst-italic">{{rate_count}}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
<!--                    End Number Review-->

                    <!--Start Vote-->
                        <div class="col-4 t-shadow px-5 " >
                            <div class="text-light text-center border border-light circle">
                                <div class="">
                                    <h3 class="h6 text-light text-center pt-2 ">Rate</h3>
                                    <h3 class="h5 fw-bold text-light text-center ">{{product_rate|floatformat:1}}/10</h3>
                                </div>
                            </div>
                        </div>
 <!--                  End Vote-->
                    <!--Start Review number-->
                        <div class="col-4 align-self-center t-shadow">
                            <div class="text-light text-center">
                                <div class="">
                                    <h3 class="h6 text-light text-center pt-3">Reviews</h3>
                                </div>

                                <div class="row">
                                    <div class="col-6 text-end">
                                        <span class="material-icons">
                                          rate_review
                                        </span>
                                    </div>
                                    <div class="col-6">
                                        <h3 class="h6 text-light text-start fst-italic">{{ number_review }}</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
<!--                    End Review Number-->
                    </div>

                </div>
                <!-- Button trigger modal -->
                <div class="pt-3">
                    <div class="align-self-center">
                        <div class="pb-3">
                            <a style="text-decoration: none" href="{% url 'ecommerce:product' id=product.id %}">
                                <span class="fst-italic text-light">See the product on our store</span>
                                <span class="material-icons text-light">
                                    storefront
                                </span>
                            </a>
                        </div>
                    </div>
                    {% if is_bought %}
                        {% if not user_review %}
                            <button type="button" class="btn btn-product-orange text-light fw-bold" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                Leave a review
                            </button>
                        {% else %}
                            <form action="{% url 'review:remove_review' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="review_id" value={{user_review.id}}>
                                <input type="hidden" name="prod_id" value={{product.id}}>
                                <button class="btn btn-danger text-light fw-bold" type="submit">Delete review</button>
                            </form>
                        {% endif %}

                    <!--    Start Form ADD Review    -->
                    <!-- Modal -->
                    <form action="{% url 'review:review' prod_id=product.id %}" method="POST">
                    {% csrf_token %}
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title h4 fw-bold paint-orange" id="exampleModalLabel">Add review</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div>
                                            <h3 class="h5">Rate:</h3>
                                            <div class="col-sm-3">
                                                <select class="form-select form-select-sm col-sm-2" name="rate" aria-label=".form-select-sm">
                                                    <option value="1" class="h6 fst-italic text-start text-secondary">1 bad</option>
                                                    <option value="2" class="h6 fst-italic text-start text-secondary">2</option>
                                                    <option value="3" class="h6 fst-italic text-start text-secondary">3</option>
                                                    <option value="4" class="h6 fst-italic text-start text-secondary">4</option>
                                                    <option value="5" class="h6 fst-italic text-start text-secondary">5 mediocre</option>
                                                    <option value="6" class="h6 fst-italic text-start text-secondary">6</option>
                                                    <option value="7" class="h6 fst-italic text-start text-secondary">7</option>
                                                    <option value="8" class="h6 fst-italic text-start text-secondary">8</option>
                                                    <option value="9" class="h6 fst-italic text-start text-secondary">9</option>
                                                    <option value="10" class="h6 fst-italic text-start text-secondary">10 unbelievable</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div>
                                            <h3 class="h5">Review:</h3>
                                            <div class="form-group">
                                                <input name="title" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Title (optional)">
                                                <textarea name="text" class="form-control" id="exampleFormControlTextarea1" placeholder="Review 750 characters max (optional)" rows="3"></textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Add review</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% endif %}
                </div>
    <!--        end modal    -->
            </div>
        </div>
    </div>

<div class="d-flex flex-row justify-content-center mb-4 mt-2">
    <div class="w-50 bg-dark bg-opacity-25 rounded">
        <div class="container mb-4 mt-2">
        <h5 class="text-white pt-2">All Ratings and Reviews</h5>
            {% for review in reviews %}
                {% if review.user == request.user %}
                  <div class="card w-100 mb-2 bg-light">
                    <div class="card-header bg-danger bg-opacity-25">
                        <h4>{{review.title}}</h4>
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">Your review ~ {{review.date|date:"d/m/Y"}}</h6>
                        <h5 class="card-text">{{review.text}}</h5>
                    </div>
                    <div class="card-footer bg-transparent">
                        <div class="row">
                            <div class="col-8">
                                <h5 class="card-text t-shadow">Rated: {{ review.rate }}/10</h5>
                            </div>
                        </div>
                    </div>
                  </div>
                 {% else %}
                    <div class="card w-100 mb-2 bg-light">
                        <div class="card-header bg-warning bg-opacity-25">
                            <h4>{{review.title}}</h4>
                        </div>
                        <div class="card-body">
                            <h6 class="card-subtitle mb-2 text-muted">{{review.user}} ~ {{review.date|date:"d/m/Y"}}</h6>
                            <h5 class="card-text">{{review.text}}</h5>
                        </div>
                        <div class="card-footer bg-transparent">
                            <div class="row">
                                <div class="col-8">
                                    <h5 class="card-text t-shadow">Rated: {{ review.rate }}/10</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        </div>
    </div>
</div>
<!-- End Container-->

{% endblock %}