customer/urls.py
from django.urls import path
from . import  views

app_name = 'customer'

urlpatterns = [
    path('keymanager', views.keymanager, name='keymanager'),
    path('library', views.library, name='library'),
    path('settings', views.profilesettings, name='settings'),
    path('signup', views.signup, name='signup'),
    path('wishlist', views.wishlist, name='wishlist'),
    path('become-seller', views.becomeseller, name='become-seller'),
    path('become-customer', views.becomecustomer, name='become-customer'),
    path('add-to-wishlist', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist', views.remove_from_wishlist, name='remove-from-wishlist'),
    path('change-pro-pic', views.change_pro_pic, name='change-pro-pic'),
    path('add-key', views.add_key, name='add-key'),
    path('delete-key', views.delete_key_by_seller, name='delete-key'),
    path('modify-key', views.modify_key, name='modify-key'),
    path('add-seller-rate', views.add_seller_rate, name='add-seller-rate')
]

ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product/<int:id>', views.product, name='product'),
    path('cart', views.cart, name='cart'),
    path('catalog/<int:page>/<int:limit>', views.catalog, {'gen': None}, name='catalog'),
    path('catalog/<str:gen>/<int:page>/<int:limit>', views.catalog, name='catalog_gen'),
    path('scout', views.scout, name='scout'),
    path('search', views.search, name='search'),
    path('add-to-cart', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart', views.remove_from_cart, name='remove-from-cart'),
    path('buy-keys', views.buy_keys, name='buy-keys'),
    path('product-add', views.product_add, name='product-add'),
]

gs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ecommerce.urls')),
    path('', include('customer.urls')),
    path('', include('review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import  views

app_name = 'review'

urlpatterns = [
    path('review/<int:prod_id>', views.review, name='review'),
    path('review/remove_review', views.remove_review, name='remove_review')
]

customer/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ecommerce.models import Product


class Profile(models.Model):
    picture = models.ImageField(db_column='Image', blank=True, null=True, help_text='Select a profile picture', upload_to='profiles/images/', default="/profiles/images/img_default.jpeg")
    seller_ratings_count = models.PositiveIntegerField(blank=True, default=0, help_text='Number of ratings given to this user')
    seller_total_ratings = models.PositiveIntegerField(blank=True, default=0)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return self.user.__str__()

    def get_absolute_url(self):
        return reverse('profile-detail', args=[str(self.id)])


class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    class Meta:
        verbose_name_plural = 'Wishlists'

    def __str__(self):
        return self.user.__str__()

    def get_absolute_url(self):
        return reverse('wishlist-detail', args=[str(self.id)])

customer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from customer.models import Profile
from ecommerce.models import Key


class SignUpForm(UserCreationForm):
    username = UsernameField(max_length=30, help_text='Insert your username. 30 characters or fewer. '
                                                      'Letters, digits and @/./+/-/_ only.')
    first_name = forms.CharField(max_length=150, help_text='Insert your first name. 150 characters or fewer.')
    last_name = forms.CharField(max_length=150, help_text='Insert your last name. 150 characters or fewer.')
    email = forms.EmailField(help_text='Insert a valid e-mail address')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email',)


class ChangeProPicForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture', 'user')


class AddKeyForm(forms.ModelForm):
    class Meta:
        model = Key
        fields= '__all__'
        exclude = ['sold']
        

customer/views.py
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.shortcuts import redirect, render
from django.db.models.aggregates import Min
from gs.settings import EMAIL_HOST_USER
from .models import Profile, Wishlist
from review.models import Review
from ecommerce.models import Product, Transaction, Key
from .forms import SignUpForm, AddKeyForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()

            if(new_user.username == 'Admin'):
                new_user.is_staff = True
                new_user.is_superuser = True
                group = Group.objects.get_or_create(name='Admins')[0]
                new_user.groups.add(group)
                new_user.save()

            new_profile = Profile(user=new_user)
            new_profile.save()
            new_wishlist = Wishlist(user=new_user)
            new_wishlist.save()
            login(request, authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1']))
            
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'customer/signup.html', {'form': form})


@login_required
def wishlist(request):
    user = request.user
    product_list_alphabetic = Product.objects.filter(wishlist__user=user).order_by('name')
    product_list_price = Product.objects.filter(wishlist__user=user).annotate(lowest_price=Min('key__sale_price')).order_by('key__sale_price')
    context = {
        'product_list_alphabetic': product_list_alphabetic,
        'product_list_price': product_list_price,
        'product_count': product_list_alphabetic.count(),
    }

    return render(request, 'customer/wishlist.html', context)


@login_required
def add_to_wishlist(request):
    user = request.user
    wishlist_user = Wishlist.objects.get(user=user)
    product_id = request.POST.get("product_id")
    wishlist_user.products.add(product_id)

    return redirect('/wishlist')


@login_required
def remove_from_wishlist(request):
    user = request.user
    wishlist_user = Wishlist.objects.get(user=user)
    product_id = request.POST.get("product_id")
    wishlist_user.products.remove(product_id)

    return redirect('/wishlist')


@login_required
def keymanager(request):
    products = Product.objects.all().order_by("name")
    keys = Key.objects.filter(seller=request.user).order_by('sold', 'product__name')
    context = {
        'products': products,
        'keys': keys,
        'keys_count': keys.count(),
    }
    
    return render(request, 'customer/keymanager.html', context)


@login_required
def add_key(request):
    if request.method == 'POST':
        post = request.POST.copy()
        post['product'] = Product.objects.get(name=post['product']).id

        if post['sale'] == '':
            post.pop('sale')

        form = AddKeyForm(post)

        if form.is_valid():
            key_instance = form.save(commit=False)
            key_instance.sale_price = key_instance.price-((key_instance.price/100)*key_instance.sale) if key_instance.sale>0 else key_instance.price
            key_instance.save()

            if key_instance.sale > 0 and key_instance.sale_price == Key.objects.filter(sold=False, product=key_instance.product).order_by('sale_price').first().sale_price:
                notified_users = User.objects.filter(wishlist__products__exact=key_instance.product)
                email_list = []
                email_text = f'{key_instance.product.name} is now on sale at €{key_instance.sale_price}.\n\nVisit our GameScout store to check the offer!'

                for user in notified_users:
                    if user != key_instance.seller:
                        email_list.append(user.email)
                    
                send_mail('A product in your wishlist got a discount!', email_text, EMAIL_HOST_USER, email_list)
    else:
        form = AddKeyForm()

    return redirect('/keymanager')


@login_required
def delete_key_by_seller(request):
    key_id = request.POST.get('key_id_to_delete')
    key_to_delete = Key.objects.get(id=key_id)

    if key_to_delete.sold == False:
        key_to_delete.delete()

    return redirect('/keymanager')


@login_required
def modify_key(request):
    key_id = request.POST.get('choose_key_modify')
    key_to_modify = Key.objects.get(id=key_id)
    key_to_modify.serial_key = request.POST.get('serial_key')
    key_to_modify.price = request.POST.get('price')
    
    if request.POST.get('sale') == '':
        key_to_modify.sale = 0
    else:    
        key_to_modify.sale = float(request.POST.get('sale'))

    if request.POST.get('sale_expiry_date') != '':
        key_to_modify.sale_expiry_date = request.POST.get('sale_expiry_date')
    
    key_to_modify.sale_price = float(key_to_modify.price)-(float(key_to_modify.price)/100)*float(key_to_modify.sale)
    key_to_modify.save()

    if key_to_modify.sale > 0 and key_to_modify.sale_price == Key.objects.filter(sold=False, product=key_to_modify.product).order_by('sale_price').first().sale_price:
        notified_users = User.objects.filter(wishlist__products__exact=key_to_modify.product)
        email_list = []
        email_text = f'{key_to_modify.product.name} is now on sale at €{key_to_modify.sale_price}.\n\nVisit our GameScout store to check the offer!'

        for user in notified_users:
            if user != key_to_modify.seller:
                email_list.append(user.email)
            
        send_mail('A product in your wishlist got a discount!', email_text, EMAIL_HOST_USER, email_list)

    return redirect('/keymanager')


@login_required
def library(request):
    transactions = Transaction.objects.filter(customer=request.user, state=Transaction.success).order_by('date_time')
    context = {
        'transactions': transactions,
        'transactions_count': transactions.count(),
    }

    return render(request, 'customer/library.html', context)


@login_required
def profilesettings(request):
    user = request.user

    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/settings')
    else:
        form = PasswordChangeForm(user)
    
    is_seller = True if user.groups.filter(name='Sellers').exists() else False
    purchased_keys_count = Transaction.objects.filter(state=Transaction.success, seller=user).count()
    review_count = Review.objects.filter(user=user).count()
    seller_keys_avaible = Key.objects.filter(seller=user, sold=False)
    seller_sold_keys_count = Key.objects.filter(seller=user, sold=True).count()
    
    while True:
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            new_profile = Profile(user=user)
            new_profile.save()
            continue
        break
    
    context = {
        'user': user,
        'is_seller': is_seller,
        'purchased_keys_count': purchased_keys_count,
        'review_count': review_count,
        'keys_avaible': seller_keys_avaible,
        'keys_avaible_count': seller_keys_avaible.count(),
        'sold_keys_count': seller_sold_keys_count,
        'seller_rate_count': profile.seller_ratings_count if user.groups.filter(name='Sellers').exists() else 0,
        'seller_rate': round(profile.seller_total_ratings/profile.seller_ratings_count, 1) if profile.seller_ratings_count!=0 else 0,
        'form': form,
    }

    return render(request, 'customer/profilesettings.html', context)


@login_required
def becomeseller(request):
    user = request.user
    group = Group.objects.get_or_create(name='Sellers')[0]
    user.groups.add(group)

    return redirect('/settings')


@login_required
def becomecustomer(request):
    user = request.user
    group = Group.objects.get_or_create(name='Sellers')[0]
    user.groups.remove(group)
    keys = Key.objects.filter(seller=user, sold=False)
    for key in keys:
        key.delete()

    return redirect('/settings')


@login_required
def change_pro_pic(request):
    user = request.user
    user_pro_pic = Profile.objects.get(user=user)
    user_pro_pic.picture = request.FILES.get('picture')
    user_pro_pic.save()

    return redirect('/settings')


@login_required
def add_seller_rate(request):
    transaction = Transaction.objects.get(id=request.POST.get('transaction_id'))
    rate = request.POST.get('rate')
    seller = Profile.objects.get(user=transaction.seller)
    transaction.is_seller_rated = True
    seller.seller_ratings_count += 1
    seller.seller_total_ratings += int(rate)
    transaction.save()
    seller.save()
    return redirect('/library')

customer/templates/customer/signup.html
{% extends "ecommerce/base.html" %}
{% block content %}

<div class="container h-150 mb-5 mt-5">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card bg-light h-100 mt-5">
            <div class="d-flex justify-content-center ">
                <div class="brand_logo_container bg-dark">
                    <img src="/media/gs_logo_mini.PNG" alt="Logo" onerror="this.onerror=null;this.src='www.goomlandscapes.co.nz/wp-content/uploads/2018/08/logo-placeholder.png';" class="brand_logo">
                </div>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form action="{% url 'customer:signup' %}" method="post">

                    {% csrf_token %}
                    <div class="text-center">
                        <h3 class="h4 fw-bold mb-4 paint-orange">
                            SIGN UP
                        </h3>
                    </div>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>Error:</strong>Invalid email and/or password don't match
                        </div>
                    {% endif %}

                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                        <input type="text" name="username" maxlength="30" autocapitalize="none" autocomplete="username" autofocus required id="id_username"class="form-control input_user" value="" placeholder="Username">
                    </div>

                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                        <input type="email" name="email" required id="id_email" class="form-control input_user" value="" placeholder="Email">
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                                <input type="text" name="first_name" maxlength="150" required id="id_first_name"class="form-control input_user" value="" placeholder="Name">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                                <input type="text" name="last_name" maxlength="150" required id="id_last_name"class="form-control input_user" value="" placeholder="Surname">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                                <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" class="form-control input-sm" placeholder="Password">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                                <input type="password" name="password2" autocomplete="new-password" required id="id_password2"class="form-control input-sm" placeholder="Confirm Password">
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <button type="submit" value="Register" class="btn login_btn">Register</button>
                    </div>
                </form>
            </div>

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account?
                </div>
                <div class="d-flex justify-content-center links">
                    <a href="{% url 'login' %}" class="ml-2">Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

customer/templates/customer/wishlist.html
{% extends "ecommerce/base.html" %}
{% load ecommerce_tags %}
{% load customer_tags %}
{% block content %}
<!--Start Container-->
<div class="container p-3">
    {% if product_count > 0 %}

<!--  Property/Sort Wishlist  -->
        <div class="d-flex justify-content-center pb-3">
            <div class="col-8">
                <h2 class="fw-bold fst-italic text-start text-light">Your wishlist:</h2>    
            </div>
        </div>
<!--   End Property Wishlist  -->

<!--     Start Wishlist   -->
        {% for product in product_list_alphabetic %}
        <!--   Start Wishlist  Bar   -->

        <div class="d-flex justify-content-center pb-5">
            <div class="position-relative">
                    <div class="position-absolute top-50 end-0 translate-middle"style="z-index: 3;">
                        <form action="{% url 'customer:remove-from-wishlist' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{product.id}}">
                            <button class="btn opacity-white material-icons cancel" type="submit">cancel</button>
                        </form>
                    </div>
            </div>
            <div class="bar-color col-8 row rounded-2 border-orange pt-2 pb-2">
                <div class="col-sm-4 align-self-center">
                    <a class="" href="{% url 'ecommerce:product' id=product.id %}">
                    <img class="w-100 border-img" src=/media/{{product.pic}} alt="Image not found" onerror="this.onerror=null;this.src='/media/products/images/img_default.jpg';">
                    </a>
                </div>

                <div class="align-self-center col-sm-3">
                    <h3 class="h4 fw-bold brand-text-color title-bar t-shadow">{{product.name}}</h3>
                        <a class="" href="{% url 'review:review' prod_id=product.id %}">
                            <div class="btn">   
                                <div class="inner-bar rounded-1 col-sm-9">
                                    <seerev>
                                    <span class="fst-italic text-light">
                                        Ratings: {{product|get_rate_count}}
                                    </span>
                                    <span class="fst-italic text-light">
                                        Rate: 
                                        {% if product|get_rate_count > 0 %}
                                            {{product|get_total_rate|floatformat:1}}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </span>
                                    </seerev>
                                </div>
                            </div>
                        </a>
                </div>

                <div class="align-self-center col-sm-3">
                    <div class="square-rev">
                        <h3 class="h6 text-light p-1">Remaining keys: {{product|get_key_count}}</h3>
                    </div>
                    <div class="square-rev">
                        <h3 class="h6 text-light p-1">Discounted keys: {{product|get_key_sale_count}}</h3>
                    </div>
                    <div class="square-rev ">
                        <h3 class="h6 text-light p-1">Highest sale: {{product|get_max_sale}} %</h3>
                    </div>
                </div>

                <div class="align-self-center col-sm-2">
                    <div class="rounded-5">
                        {% if product|get_key_count > 0 %}
                            <form action="{% url 'ecommerce:add-to-cart' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-lg btn-primary btn-humble-orange"style="height: 125px" type="submit">
                                    <input type="hidden" name="product_id" value="{{product.id}}">
                                    <input type="hidden" name="key_id" value="">
                                    <addtocar class="btn fw-bold text-light">
                                        <div class="text-center text-light">
                                            <span class="h6 ">Best price</span>
                                            {% with product|get_best_price as best_price %}
                                                <span class="h5 fw-bold">€{{best_price.sale_price|floatformat:2}}</span>
                                            {% endwith %}
                                        </div>
                                    </addtocar>
                                    </form>
                                </button>
                            </form>
                        {% else %}
                            <button class="btn btn-lg btn-primary btn-humble-orange" style="height: 125px" disabled>
                                <div class="row">
                                    <div class="justify-content-center">
                                        <h3 class="h6 text-light text-center">Out of stock</h3>
                                    </div>
                                </div>
                            </button>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
<!--   End Whishlist Bar   -->
        {% endfor %}
<!--    End Whishlist    -->
        {% else %}
            <div class="justify-content-center">
                <h5 class="text-light text-center t-shadow">Your wishlist is empty</h5>
            </div>
        {% endif %}
</div>
<!-- End Container-->
{% endblock %}