customer/urls.py
from django.urls import path
from . import  views

app_name = 'customer'

urlpatterns = [
    path('keymanager', views.keymanager, name='keymanager'),
    path('library', views.library, name='library'),
    path('settings', views.profilesettings, name='settings'),
    path('signup', views.signup, name='signup'),
    path('wishlist', views.wishlist, name='wishlist'),
    path('become-seller', views.becomeseller, name='become-seller'),
    path('become-customer', views.becomecustomer, name='become-customer'),
    path('add-to-wishlist', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist', views.remove_from_wishlist, name='remove-from-wishlist'),
    path('change-pro-pic', views.change_pro_pic, name='change-pro-pic'),
    path('add-key', views.add_key, name='add-key'),
    path('delete-key', views.delete_key_by_seller, name='delete-key'),
    path('modify-key', views.modify_key, name='modify-key'),
    path('add-seller-rate', views.add_seller_rate, name='add-seller-rate')
]

ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product/<int:id>', views.product, name='product'),
    path('cart', views.cart, name='cart'),
    path('catalog/<int:page>/<int:limit>', views.catalog, {'gen': None}, name='catalog'),
    path('catalog/<str:gen>/<int:page>/<int:limit>', views.catalog, name='catalog_gen'),
    path('scout', views.scout, name='scout'),
    path('search', views.search, name='search'),
    path('add-to-cart', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart', views.remove_from_cart, name='remove-from-cart'),
    path('buy-keys', views.buy_keys, name='buy-keys'),
    path('product-add', views.product_add, name='product-add'),
]

gs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ecommerce.urls')),
    path('', include('customer.urls')),
    path('', include('review.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path
from . import  views

app_name = 'review'

urlpatterns = [
    path('review/<int:prod_id>', views.review, name='review'),
    path('review/remove_review', views.remove_review, name='remove_review')
]

ecommerce/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
    name = models.CharField(unique=True, max_length=64, help_text='Enter a product category (e.g. OS, game)')

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])


class Genre(models.Model):
    name = models.CharField(unique=True, max_length=64, help_text='Enter a product genre')

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Genres'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class Developer(models.Model):
    name = models.CharField(unique=True, max_length=64, help_text='Enter a product developer')

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Developers'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class Publisher(models.Model):
    name = models.CharField(unique=True, max_length=64, help_text='Enter a product publisher')
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Publishers'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class Product(models.Model):
    name = models.CharField(max_length=64, help_text='Enter product name')
    publishing_date = models.DateField(help_text='Enter the product publishing date')
    description = models.TextField(blank=True, null=True, help_text='Enter a description for the product')
    pic = models.ImageField(db_column='Image', blank=True, null=True, help_text='Select a picture for the product', upload_to="products/images/", default="/products/images/img_default.jpeg")
    
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, help_text='Enter a product category')
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL, help_text='Enter a product genre')
    developer = models.ForeignKey(Developer, null=True, on_delete=models.SET_NULL,
                                  help_text='Enter the product developer')
    publisher = models.ForeignKey(Publisher, null=True, on_delete=models.SET_NULL,
                                  help_text='Enter the product publisher')

    class Meta:
        ordering = ['name', '-publishing_date']
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])


class Key(models.Model):
    serial_key = models.CharField(unique=True, max_length=64, help_text='Enter the serial key')
    price = models.DecimalField(max_digits=10, decimal_places=2, help_text='Enter the price for the key')
    sale = models.IntegerField(default=0, blank=True, validators=[MinValueValidator(0), MaxValueValidator(100)],
                                       help_text='Enter the sale value')
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    sale_expiry_date = models.DateTimeField(blank=True, null=True)
    sold = models.BooleanField(default=False)
    
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    seller = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['product', 'serial_key']
        verbose_name_plural = 'Keys'

    def __str__(self):
        return self.serial_key

    def get_absolute_url(self):
        return reverse('key-detail', args=[str(self.id)])


class Transaction(models.Model):
    # Payment method allowed for transaction
    visa = 'VISA'
    mastercard = 'MASTERCARD'
    maestro = 'MAESTRO'
    paypal = 'PAYPAL'

    PAY_METHOD = [
        (visa, 'Visa'),
        (mastercard, 'MasterCard'),
        (maestro, 'Maestro'),
        (paypal, 'PayPal'),
    ]

    # Transaction states allowed
    success = 'SUCCESS'
    pending = 'PENDING'
    failure = 'FAILURE'

    STATES = [
        (success, 'Success'),
        (pending, 'Pending'),
        (failure, 'Failure'),
    ]

    date_time = models.DateTimeField(blank=True, default=datetime.now)
    payment_method = models.CharField(choices=PAY_METHOD, blank=True, null=True, max_length=16,
                                      help_text='Choose the payment method')
    state = models.CharField(choices=STATES, default='Pending', max_length=16)
    is_seller_rated = models.BooleanField(blank=True, default=False)
    key = models.OneToOneField(Key, null=True, on_delete=models.SET_NULL)
    customer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='customer')
    seller = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='seller')

    class Meta:
        unique_together = (('id', 'key'),)
        ordering = ['-date_time']
        verbose_name_plural = 'Transactions'

    def __str__(self):
        return self.key.__str__()

    def get_absolute_url(self):
        return reverse('transaction-detail', args=[str(self.id)])

ecommerce/forms.py
from django import forms
from ecommerce.models import Product


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

ecommerce/views.py
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.utils import IntegrityError
from django.db.models import Max, Count, Sum, Q, FloatField
from django.db.models.functions import Cast
from django.shortcuts import redirect, render, get_object_or_404
from datetime import datetime
from background_task.models import Task
from ecommerce.forms import AddProductForm
from ecommerce.models import Category, Developer, Product, Genre, Key, Publisher, Transaction
from ecommerce.tasks import t_remove_from_cart
from gs.settings import EMAIL_HOST_USER
from review.models import Review


@login_required
def cart(request):
    transaction_list = Transaction.objects.filter(customer=request.user, state=Transaction.pending).order_by('-date_time')
    total_real_cost = 0
    total_cost = 0

    for transaction in transaction_list:
        total_real_cost += transaction.key.sale_price
        total_cost += transaction.key.price

    context = {
        'transaction_list': transaction_list,
        'transaction_count': transaction_list.count(),
        'total_real_cost': round(total_real_cost, 2),
        'total_cost': round(total_cost, 2),
        'payment_method': [Transaction.visa, Transaction.mastercard, Transaction.maestro, Transaction.paypal],
    }

    return render(request, 'ecommerce/cart.html', context)


@login_required
def add_to_cart(request):
    user = request.user
    key_id = request.POST.get('key_id')
    
    if(key_id != ''):
        key = Key.objects.get(id=key_id)
    else:
        product_id = request.POST.get('product_id')
        key = Key.objects.filter(product__id=product_id).order_by('sale_price').first()
    
    if(key):
        seller = User.objects.get(username=key.seller)
        
        try:
            new_transaction = Transaction(state=Transaction.pending , key=key, customer=user, seller=seller)
            new_transaction.save()
            t_remove_from_cart(new_transaction.id)
        except IntegrityError:
            return redirect(f'/product/{key.product.id}')

    return redirect('/cart')


@login_required
def remove_from_cart(request):
    transaction_id = request.POST.get("transaction_id")
    transaction_to_remove = Transaction.objects.filter(id=transaction_id)
    transaction_to_remove.delete()
    task_parms = '[[' + transaction_id + '], {}]'
    task_to_remove = Task.objects.get(task_params=task_parms)
    task_to_remove.delete()

    return redirect('/cart')


@login_required
def buy_keys(request):
    user = request.user
    pay_method = request.POST.get("pay_method")
    transaction_list = Transaction.objects.filter(customer=user, state=Transaction.pending)
    email_text = 'You bought these products from our site:\n\n'

    for transaction in transaction_list:
        key_sold = Key.objects.get(serial_key=transaction.key)
        key_sold.sold = True
        key_sold.save()

        if pay_method == 'Visa':
            transaction.payment_method = Transaction.visa
        elif pay_method == 'MasterCard':
            transaction.payment_method = Transaction.mastercard
        elif pay_method == 'Maestro':
            transaction.payment_method = Transaction.maestro
        elif pay_method == 'PayPal':
            transaction.payment_method = Transaction.paypal

        transaction.date_time = datetime.now()
        transaction.state = Transaction.success
        transaction.save()
        email_text += f'€{key_sold.sale_price}   {key_sold.product}\n'
    
    if transaction_list.exists():
        email_text += '\nLeave a review on GameScout!'
        try:
            send_mail('Your order on GameScout', email_text, EMAIL_HOST_USER, [user.email])
        except:
            print('Email not sent')

    return redirect('/cart')


def product(request, id):
    keys = Key.objects.filter(product_id=id, sold=False).exclude(transaction__state=Transaction.pending).order_by('sale_price')
    current_product = get_object_or_404(Product, pk=id)
    reviews_q = Review.objects.filter(product_id=id)
    rate_count = reviews_q.count()
    current_reviews = reviews_q.exclude(title__isnull=True)
    review_count = current_reviews.count()
    total_rate = reviews_q.aggregate(Sum('rate'))["rate__sum"] or 0
    product_rate = total_rate / review_count if review_count != 0 else 0
    context = {
        'product': current_product,
        'keys': keys,
        'keys_count': keys.count(),
        'rate_count': rate_count,
        'review_count': review_count,
        'review_product_rate': total_rate,
        'product_rate': product_rate,
    }

    return render(request, 'ecommerce/product.html', context)


def homepage(request):
    products = Product.objects.annotate(Count('key')).filter(key__sold=False, key__count__gt=0)
    most_sold = products.filter(key__transaction__state=Transaction.success).annotate(Count('key__transaction')).order_by('-key__transaction__count')[:3]
    big_sales = products.annotate(Max('key__sale')).filter(key__sale__max__gt=0).order_by('-key__sale__max')[:10]
    lastests = products.order_by('-publishing_date')[:10]
    top_rated = products.annotate(product_rate=(Cast(Sum('review__rate'), FloatField())/Cast(Count('review'), FloatField()))).order_by('-product_rate')[:10]
    context = {
        'most_sold_list': most_sold,
        'big_sales_list': big_sales,
        'lastests_list': lastests,
        'top_rated_list': top_rated,
    }

    return render(request, 'ecommerce/homepage.html', context)


def catalog(request, limit, page, gen):
    products = Product.objects.annotate(Count('key')).filter(key__sold=False, key__count__gt=0).order_by('name')
    genre = None

    if gen:
        genre = Genre.objects.get(name=gen)
        products = products.filter(genre=genre)

    paginator = Paginator(products, limit)
    current_page = paginator.get_page(page)
    genres = Genre.objects.all()
    context = {
        'current_page': current_page,
        'paginator': paginator,
        'limit': limit,
        'genres': genres,
        'selected_genre': genre,
        'available_limits': [10, 20, 30, 40, 50],
        'not_first_page': current_page.has_previous(),
        'not_last_page': current_page.has_next(),
    }

    return render(request, 'ecommerce/catalog.html', context)


@login_required
def scout(request):
    user = request.user
    relevant_genres = Genre.objects.filter(product__key__transaction__customer=user, product__key__transaction__state=Transaction.success).annotate(intensity=Count('product')).order_by('-intensity')[:3]
    base_q = Product.objects.exclude(key__transaction__customer=user).alias(Count('key'))
    intrested_prod_q = base_q.filter(key__count__gt=0, genre__in=relevant_genres)
    most_sold_intrested_products = intrested_prod_q.annotate(key_sold=Count('key__transaction', filter=Q(key__transaction__state=Transaction.success))).order_by('-key_sold')[:5]
    not_intrested_prod_q = base_q.filter(key__count__gt=0).exclude(genre__in=relevant_genres)
    not_intrested_most_sold = not_intrested_prod_q.annotate(key_sold=Count('key__transaction', filter=Q(key__transaction__state=Transaction.success))).order_by('-key_sold')[:12]
    context = {
                'intrest_most_sold': most_sold_intrested_products,
                'not_intrest_most_sold': not_intrested_most_sold, 
               }

    return render(request, 'ecommerce/scout.html', context)


def search(request):
    q = request.GET.get('q')
    products = Product.objects.filter(name__contains=q).order_by('name')
    context = {
                'search': q,
                'products': products,
                'products_count': products.count() if products != None else 0,
    }

    return render(request, 'ecommerce/search.html', context)


def product_add(request):
    if request.method == 'POST':
        post = request.POST.copy()
        post['publisher'] = Publisher.objects.get_or_create(name=post['publisher'])[0].id
        post['developer'] = Developer.objects.get_or_create(name=post['developer'])[0].id
        post['category'] = Category.objects.get_or_create(name=post['category'])[0].id
        post['genre'] = Genre.objects.get_or_create(name=post['genre'])[0].id
        form = AddProductForm(post, request.FILES)

        if form.is_valid():
            product = form.save()

            return redirect(f'/product/{product.id}')
    else:
        form = AddProductForm()

    publishers = Publisher.objects.all().order_by('name')
    developers = Developer.objects.all().order_by('name')
    categories = Category.objects.all().order_by('name')
    genres = Genre.objects.all().order_by('name')
    context = {
        'form': form,
        'publishers': publishers,
        'developers': developers,
        'categories': categories,
        'genres': genres,
    }

    return render(request, 'ecommerce/product_add.html', context)

ecommerce/templates/ecommerce/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--    google fonts-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <!--  style css -->
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/catalog.css' %}">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'css/keymanager.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/product.css' %}">
    <link rel="stylesheet" href="{% static 'css/profilesettings.css' %}">
    <link rel="stylesheet" href="{% static 'css/wishlist.css' %}">
    <link rel="stylesheet" href="{% static 'css/logout.css' %}">


    {% load is_seller from ecommerce_tags %}
    {% load is_admin from ecommerce_tags %}
    <title>GameScout - Buy cheapest keys</title>
</head>
<body>
<!--navbar-->
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark" style="height: 65px">
    <div class="container">
        <a class="navbar-brand" href="{% url 'ecommerce:homepage' %}">
            <img src="/media/gs_logo.jpg" alt="Image not found" onerror="this.onerror=null;this.src='www.goomlandscapes.co.nz/wp-content/uploads/2018/08/logo-placeholder.png';" width="100"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-dark bg-dark navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item px-2">
                    <a class="nav-link"href="/">Home</a>
                </li>

                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'ecommerce:catalog' limit=20 page=1 %}">Catalog</a>
                </li>

                <li class="nav-item px-2">
                    <a class="nav-link"href="{% url 'ecommerce:scout' %}">Scout</a>
                </li>
            </ul>

            <ul class="navbar-nav mr-0 mb-2 mb-lg-0">
                {% if not user.is_authenticated %}
                <li class="nav-item px-2">
                    <a class="nav-link"href="{% url 'login' %}">
                        <span class="material-icons text-light opacity-white">
                            shopping_cart
                        </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item px-2">
                    <a class="nav-link"href="{% url 'ecommerce:cart' %}">
                        <div class="position-relative">
                            <div class="position-absolute top-0 start-0 translate-middle text-ligt fw-bold">{{transaction_count}}</div>
                        </div>
                        <span class="material-icons text-light opacity-white">
                            shopping_cart
                        </span>
                    </a>
                </li>
                {% endif %}


                {% if not user.is_authenticated %}
                <li class="nav-item px-2">
                    <a class="nav-link"href="{% url 'login' %}">
                        <span class="material-icons text-light opacity-white">
                            favorite_border
                        </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item px-2">
                    <a class="nav-link"href="{% url 'customer:wishlist' %}">
                        <div class="position-relative">
                            <div class="position-absolute top-0 start-0 translate-middle fw-bold">{{wishlist_count}}</div>
                        </div>
                        <span class="material-icons text-light opacity-white">
                            favorite_border
                        </span>
                    </a>
                </li>
                {% endif %}

            </ul>

            <ul class="navbar-nav mr-0 mb-2 mb-lg-0">
                <li class="nav-item ml-auto px-2">
                    <form action="{% url 'ecommerce:search' %}" class="d-flex">
                        <label for="search"></label>
                        <input class="form-control me-2" id="search" name="q" type="search">
                        <button class="btn btn-outline-success color-orange" type="submit">Search</button>
                    </form>
                </li>

                {% if not user.is_authenticated %}
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'customer:signup' %}">Sign Up</a>
                </li>

                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                </li>
                {% else %}
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="nav-dropdown-about">
                        <li><a class="dropdown-item" href="{% url 'customer:library' %}">Library</a></li>
                        {% if user|is_seller %}
                            <li><a class="dropdown-item" href="{% url 'customer:keymanager' %}">Key manager</a></li>
                        {% endif %}
                        {% if user|is_admin %}
                            <li><a class="dropdown-item" href="{% url 'ecommerce:product-add' %}">Add product</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'customer:settings' %}">Settings</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>


{% block content %}
<p><strong>Notice:</strong> no content available</p>
{% endblock %}

<!-- Import scripts -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#datepicker').datepicker();
    });
</script>
<!-- Start Footer -->
<body class="d-flex flex-column min-vh-100">
    <footer class="mt-auto text-center text-white" style="background-color: rgba(0, 0, 0, 0.2)">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" role="button">
                <i class="fab fa-facebook-f"></i>
            </a>

            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.twitter.com" role="button">
                <i class="fab fa-twitter"></i>
            </a>

            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.google.com" role="button">
                <i class="fab fa-google"></i>
            </a>

            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com" role="button">
                <i class="fab fa-instagram"></i>
            </a>

            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com" role="button">
                <i class="fab fa-linkedin-in"></i>
            </a>

            <!-- Gitlab -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://gitlab.com/HellsMike/game-scout" role="button">
                <i class="fab fa-gitlab"></i>
            </a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3 bg-dark">
            <div class="row d-flex align-items-center">
                <div class="col-md-4">
                    <i style="color: #d28c46" class="fas fa-map-marker-alt fa-fw"></i>
                    Modena
                </div>
                <div class="col-md-4">
                    <img style="width: 15%;" src="/media/gs_logo_mini.PNG" alt="Logo" onerror="this.onerror=null;this.src='www.goomlandscapes.co.nz/wp-content/uploads/2018/08/logo-placeholder.png';">
                </div>
                <div class="col-md-4">
                    <a class="text-decoration-none text-white" href="mailto:gamescout.tecweb@gmail.com">
                        <i style="color: #d28c46" class="fa fa-envelope fa-fw"></i>
                        gamescout.tecweb@gmail.com
                    </a>
                </div>
            </div>
        </div>
        <!-- Copyright -->
    </footer>
</body>
<!-- End Footer -->

{% block javascript %} {% endblock %}

</body>
</html>

ecommerce/templates/ecommerce/search.html
{% extends "ecommerce/base.html" %}
{% block content %}
{% load ecommerce_tags %}
<div class="container">

    <div class="row my-3">
        <div class="col-md-12 px-2">
            <h2 class="fst-italic text-secondary">You searched: {{search}}</h2>
        </div>
    </div>

    {% if products_count == 0 %}
    <div class="row p-5">
        <div class="justify-content-center">
            <h3 class="h3 text-secondary text-start">No relevant resoults</h3>
        </div>
    </div>
    {% else %}

    <div class="row">

    {%for product in products%}
    <div class="col-md-3 pb-3">
            <div class="card w-100 rounded border border-light catalog-card-little" style="background-image:url({{product.pic.url}})">
                <div class="position-absolute top-0 start-0 p-1">
                    {% with product.id|get_best_price as best_product %} 
                        {% if best_product.sale > 0 %}
                            <span class="badge rounded-pill btn-product-orange"> {{ best_product.sale }} %</span>
                        {% endif %}
                </div>
                <div class="card-content-little">
                    <h3 class="t-shadow text-light">{{product.name}}</h3>
                    <div>
                        <div class="row pt-3">
                            <div class="col-12 ">
                                <h3 class="h6 text-light">Best price</h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <h3 class="h4 text-light t-shadow ">€ {{best_product.sale_price}}</h3>
                            </div>
                    {% endwith %}
                            <div class="col-6">
                                <a href="{% url 'ecommerce:product' id=product.id %}" class="btn catalog-button">
                                    <span class="h6 text-light">Learn more</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="position-absolute top-0 end-0 p-1">
                    <form action="{% url 'customer:add-to-wishlist' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{product.id}}">
                        <button class="btn opacity-white material-icons heart" type="submit">favorite</button>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endif %}

    </div>
</div>
{% endblock %}